version: "2"
linters:
  default: standard
  enable:
    - bidichk
    - bodyclose
    - canonicalheader
    - containedctx
    - contextcheck
    - copyloopvar
    - durationcheck
    - err113
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - exptostd
    - gocheckcompilerdirectives
    - gocritic
    - godot
    - gosec
    - govet
    - iface
    - intrange
    - noctx
    - nolintlint
    - nosprintfhostport
#    - paralleltest
    - perfsprint
    - prealloc
    - predeclared
    - reassign
    - staticcheck
    - tagalign
    - testableexamples
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unparam
    - usestdlibvars
    - usetesting
    - wastedassign
    - whitespace
    - wrapcheck